# Generated by Django 4.2.5 on 2023-09-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress1',
            field=models.ForeignKey(default='Katowice', on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
